name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install poetry
      
      - name: Install dependencies with Poetry
        run: poetry install
      
      - name: Run static analysis
        run: poetry run pycodestyle .
      
      - name: Run tests
        run: poetry run coverage run --branch --module unittest discover --verbose

      - name: Generate coverage report
        run: poetry run coverage xml
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
